services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0.5236-ls137
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - /mnt/user/appdata/prowlarr:/config
    environment:
      - PUID=99
      - PGID=100
      - TZ=Australia/Adelaide
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:prowlarr
      - TP_THEME=nord
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/Prowlarr/Prowlarr/refs/heads/develop/Logo/1024.png"
        net.unraid.docker.webui: "http://[IP]:[PORT:9696]"

  radarr:
    image: lscr.io/linuxserver/radarr:6.0.4.10291-ls293
    container_name: radarr
    restart: unless-stopped
    ports:
      - "7878:7878"
    volumes:
      - /mnt/user/appdata/radarr:/config
      - /mnt/user/media:/media
    environment:
      - PUID=99
      - PGID=100
      - TZ=Australia/Adelaide
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:radarr
      - TP_THEME=nord
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/radarr/radarr/refs/heads/develop/Logo/1024.png"
        net.unraid.docker.webui: "http://[IP]:[PORT:7878]"

  sonarr:
    image: lscr.io/linuxserver/sonarr:4.0.16.2944-ls303
    container_name: sonarr
    restart: unless-stopped
    ports:
      - "8989:8989"
    volumes:
      - /mnt/user/appdata/sonarr:/config
      - /mnt/user/media:/media
    environment:
      - PUID=99
      - PGID=100
      - TZ=Australia/Adelaide
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:sonarr
      - TP_THEME=nord
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/Sonarr/Sonarr/refs/heads/develop/Logo/1024.png"
        net.unraid.docker.webui: "http://[IP]:[PORT:8989]"

  lidarr:
    image: lscr.io/linuxserver/lidarr:3.1.0.4875-ls20
    container_name: lidarr
    restart: unless-stopped
    ports:
      - "8686:8686"
    volumes:
      - /mnt/user/appdata/lidarr:/config
      - /mnt/user/media:/media
    environment:
      - PUID=99
      - PGID=100
      - TZ=Australia/Adelaide
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:lidarr
      - TP_THEME=nord
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/Lidarr/Lidarr/refs/heads/develop/Logo/1024.png"
        net.unraid.docker.webui: "http://[IP]:[PORT:8686]"

  profilarr:
    image: ghcr.io/dictionarry-hub/profilarr:develop
    container_name: profilarr
    restart: unless-stopped
    ports:
      - "6868:6868"
    volumes:
      - /mnt/user/appdata/profilarr:/config
    environment:
      - PUID=99
      - PGID=100
      - TZ=Australia/Adelaide
      - PARSER_HOST=profilarr-parser
      - PARSER_PORT=5000
    depends_on:
      profilarr-parser:
        condition: service_healthy
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/Dictionarry-Hub/profilarr/refs/heads/v2/src/lib/client/assets/logo-512.png"
        net.unraid.docker.webui: "http://[IP]:[PORT:6868]"

  profilarr-parser:
    image: ghcr.io/dictionarry-hub/profilarr-parser:develop
    container_name: profilarr-parser
    restart: unless-stopped
    expose:
      - "5000"
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/Dictionarry-Hub/profilarr/refs/heads/v2/src/lib/client/assets/logo-512.png"

  seerr:
    image: ghcr.io/seerr-team/seerr:v3.0.1
    init: true
    container_name: seerr
    user: "99:100"
    restart: unless-stopped
    ports:
      - "5055:5055"
    volumes:
      - /mnt/user/appdata/seerr:/app/config
    environment:
      - LOG_LEVEL=debug
      - TZ=Australia/Adelaide
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/seerr-team/seerr/develop/public/android-chrome-512x512.png"
        net.unraid.docker.webui: "http://[IP]:[PORT:5055]"

  tracearr:
    image: ghcr.io/connorgallopo/tracearr:supervised
    container_name: tracearr
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - /mnt/user/appdata/tracearr:/config
    environment:
      - TZ=Australia/Adelaide
    labels:
        net.unraid.docker.icon: "https://tracearr.com/images/logo-transparent.png"
        net.unraid.docker.webui: "http://[IP]:[PORT:3000]"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:5.1.4-r2-ls442
    container_name: qbittorrent
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "50413:50413"
    volumes:
      - /mnt/user/appdata/qbittorrent:/config
      - /mnt/user/media:/media
    environment:
      - PUID=99
      - PGID=100
      - TZ=Australia/Adelaide
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:qbittorrent
      - TP_THEME=nord
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/binhex/docker-templates/master/binhex/images/qbittorrent-icon.png"
        net.unraid.docker.webui: "http://[IP]:[PORT:8080]"

  qui:
    image: ghcr.io/autobrr/qui:v1.14.1
    container_name: qui
    restart: unless-stopped
    ports:
      - "7476:7476"
    volumes:
      - /mnt/user/appdata/qui:/config
      - /mnt/user/media:/media
    environment:
      - TZ=Australia/Adelaide
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/autobrr/qui/refs/heads/develop/documentation/static/img/qui.png"
        net.unraid.docker.webui: "http://[IP]:[PORT:7476]"

  plex:
    image: lscr.io/linuxserver/plex:1.43.0.10492-121068a07-ls294
    container_name: plex
    restart: unless-stopped
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/user/appdata/plex:/config
      - /mnt/user/media:/media
    environment:
      - PUID=99
      - PGID=100
      - TZ=Australia/Adelaide
      - VERSION=docker
    labels:
        net.unraid.docker.icon: "https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/plex-logo.png"
        net.unraid.docker.webui: "http://[IP]:32400/web"
