services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:2.3.0.5236-ls137
    container_name: prowlarr
    restart: unless-stopped
    ports:
      - "9696:9696"
    volumes:
      - /mnt/user/appdata/prowlarr:/config
    environment:
      - PUID=99
      - PGID=100
      - TZ=Australia/Adelaide
      - DOCKER_MODS=ghcr.io/themepark-dev/theme.park:prowlarr
      - TP_THEME=nord