services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /mnt/user/appdata/kavita:/config
      - /mnt/user/media:/data
    environment:
      - PUID=99
      - PGID=100
      - TZ=Australia/Adelaide
    networks:
      - gateway
    labels:
      net.unraid.docker.icon: "https://cdn.jsdelivr.net/gh/selfhst/icons@main/png/kavita.png"
      net.unraid.docker.webui: "http://kavita.orion"
      traefik.enable: "true"
      traefik.docker.network: "gateway"
      traefik.http.routers.kavita.rule: "Host(`kavita.orion`)"
      traefik.http.services.kavita.loadbalancer.server.port: "5000"

networks:
  gateway:
    external: true
