services:
  traefik:
    image: traefik:v3.6.9
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80/tcp"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
    environment:
      - TZ=Australia/Adelaide
    networks:
      - gateway
    labels:
      net.unraid.docker.icon: "https://raw.githubusercontent.com/traefik/traefik/master/docs/content/assets/img/traefik.logo.png"
      net.unraid.docker.webui: "http://traefik.orion/dashboard/"
      traefik.enable: "true"
      traefik.http.routers.traefik.rule: "Host(`traefik.orion`)"
      traefik.http.routers.traefik.service: "api@internal"

networks:
  gateway:
    name: gateway
